# Schema for the configuration files of the Sitemap module.

sitemap.settings:
  langcode: 'en'
  type: config_object
  label: 'Sitemap settings'
  mapping:
    page_title:
      type: string
      label: 'Page title'
    include_css:
      type: boolean
      label: 'Include css file flag'
    message:
      type: mapping
      label: 'Message'
      mapping:
        format:
          type: string
          label: 'Sitemap message format'
        value:
          type: string
          label: 'Sitemap message string'
    plugins:
      type: sequence
      label: 'Plugins'
      nullable: true
      sequence:
        type: sitemap.settings.plugins.[%key]
    plugin_settings__active_tab:
      type: string
      label: 'Plugin settings active tab'
    submit:
      type: string
      label: 'Save configuration'
    form_build_id:
      type: string
      label: 'Form build ID'
    form_token:
      type: string
      label: 'Form token'
    form_id:
      type: string
      label: 'sitemap_settings'
    op:
      type: string
      label: 'Save configuration'

#    show_titles:
#      type: boolean
#      label: 'Show titles flag'
#    show_books:
#      type: sequence
#      label: 'Books to display'
#      sequence:
#        - type: integer
#          label: 'Book id'
#    books_expanded:
#      type: boolean
#      label: 'Books expanded flag'
#    show_menus:
#      type: sequence
#      label: 'Menus to display'
#      sequence:
#        - type: string
#          label: 'Menu id'
#    show_menus_hidden:
#      type: boolean
#      label: 'Show disabled menu items flag'
#    show_vocabularies:
#      type: sequence
#      label: 'Vocabularies to display'
#      sequence:
#        - type: string
#          label: 'Vocabulary id'
#    show_description:
#      type: boolean
#      label: 'Show vocabulary description flag'
#    show_count:
#      type: boolean
#      label: 'Show node count by taxonomy term flag'
#    vocabulary_depth:
#      type: integer
#      label: 'Vocabulary depth'
#    term_threshold:
#      type: integer
#      label: 'Term count threshold'
#    forum_threshold:
#      type: integer
#      label: 'Forum count threshold'
#    rss_front:
#      type: label
#      label: 'RSS front'
    rss_display:
      type: string
      label: 'Position of RSS links'
#    rss_taxonomy:
#      type: integer
#      label: 'RSS depth'
#    order:
#      type: sequence
#      label: 'Sitemap order'
#      sequence:
#        - type: sitemap.order.[%key]
#
#sitemap.order.*:
#  type: integer
#  label: 'Weight'
#
system.menu.*.third_party.sitemap:
  type: mapping
  label: 'Menu customizations'
  mapping:
    sitemap_display_name:
      type: text
      label: 'Sitemap display name'

sitemap.settings.plugins.*:
  type: mapping
  label: 'Sitemap plugin'
  mapping:
    enabled:
      type: integer
      label: 'Enabled'
    weight:
      type: string
      label: 'Weight'
    settings:
      type: sequence
      label: 'Settings'
      nullable: true
      sequence:
        - type: string
          label: 'Title'
