<?php

/**
 * @filesource File contains details of Hook for Import and Export functionality code.
 */

/**
 * Declaring classes.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_form_alter().
 *
 * Exposed filter form altered for Including Download option and Date filter.
 * 
 */
function excel_import_export_form_alter(&$form, FormStateInterface $form_state) {
  if (($form["#id"] == "views-exposed-form-officers-application-list-page-1") && ($form["#form_id"] == "views_exposed_form")) {
    $arg = explode('/', \Drupal::request()->getpathInfo());
    $url = URL::fromUserInput('/excel/content/application/export')->toString() . '?tid=' . $arg[2];
    $created = $_GET['created'];
    if (isset($_GET['created'])) {
      $url = $url . '&min=' . $created['min'] . '&max=' . $created['max'];
    }
    $form['created']['min']['#type'] = 'date';
    $form['created']['max']['#type'] = 'date';
    $form['export'] = array(
      '#type' => 'markup',
      '#markup' => '<a href="' . $url . '">Export</a>',
      '#suffix' => t('Note: During export, applications have Applied, Need More Info and Details Appended status will exports.'),
      '#submit' => array('excel_import_export_submit_handler'),
      '#weight' => 100,
    );
     $form['#validate'][] ='validation';
  } 
}

/**
 *
 * Helper function for unserialize nids.
 * 
 */
function excelImportExportUnserialize($nodeArray) {
  $nids = unserialize($nodeArray);
  $nidArray = array();
  if (!empty($nids)) {
    foreach ($nids as $nid) {
     $nidArray[] = $nid;
    }
  }
  return $nidArray;
}

/**
 *
 * Date Validation.
 * 
 */
function validation(&$form, FormStateInterface $form_state){
  $min = strtotime($form['created']['min']['#value']);
  $max = strtotime($form['created']['max']['#value']);
  if(!empty($max)){
    if($min > $max){
      $form_state->setError($form['created']['min'],"From Date is Should Not be Lower than To Date");
    }
  }
}
