<?php

/**
 * @file
 * Provides sitemap functionality.
 */

/**
 * Implements hook_theme().
 */
function sitemap_theme() {
  return [
    'sitemap' => [
      'variables' => [
        'message' => NULL,
        'sitemap_items' => [],
      ],
      'file' => 'sitemap.theme.inc',
    ],
    'sitemap_feed_icon' => [
      'variables' => [
        'url' => NULL,
        'name' => NULL,
        'type' => 'node',
      ],
      'file' => 'sitemap.theme.inc',
    ],
    'sitemap_menu_link' => [
      'render element' => 'element',
      'function' => 'theme_sitemap_menu_link',
      'file' => 'sitemap.theme.inc',
    ],
    'sitemap_menu_tree' => [
      'render element' => 'tree',
      'function' => 'theme_sitemap_menu_tree',
      'file' => 'sitemap.theme.inc',
    ],
    'sitemap_item' => [
      'variables' => [
        'title' => '',
        'content' => [],
        'sitemap' => '',
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function template_preprocess_sitemap_item(&$variables) {
  // @TODO; global prepreocess or per-type preprocess?
  // @TODO: Move to sitemap.theme.inc if keeping.
}

/**
 * Count the number of published nodes classified by a term.
 *
 * This is a re-implementation of taxonomy_term_count_nodes() that has been
 * removed from D7 core.
 *
 * Implementation note: the normal way to count field instances is through
 * field_attach_query(), but taxonomy.module has a special denormalized
 * table taxonomy_index which we can use for more speed. THX to taxonews.
 *
 * @param string $tid
 *   The term's ID.
 *
 * @return string
 *   An integer representing a number of nodes. Results are statically cached.
 */
function sitemap_taxonomy_term_count_nodes($tid) {
  $query = \Drupal::database()->select('taxonomy_index', 'ti');
  $query->addExpression('COUNT(ti.nid)');
  $count = $query
    ->condition('ti.tid', $tid)
    ->execute()->fetchCol();
  return $count[0];
}
