admin_emails: null
admin:
  subject: 'New order placed'
  body: "Hi, \n An order was placed by [node:title] [basiccart_order:basiccart_email]\nOrdered products:\n[basiccart_order:products]\nTotal price: [basiccart_order:basiccart_total_price]"
send_emailto_user: 0
user:
  subject: 'New order placed'
  body: "Hi,\nYou just placed an order on the website [site:name]. Here are the order details:\n[basiccart_order:products]\nTotal price: [basiccart_order:basiccart_total_price]\nWe will contact you as soon as possible."
thankyou:
  title: 'Thank you'
  text: "Thank you for placing an order on our website.\nWe will contact you as soon as possible."
langcode: en
_core:
  default_config_hash: vWHcP6sCKFEwraU53aUXU3kgrvI6l4m9g6x36PQJMWU
