module:
  action: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  ban: 0
  basiccart: 0
  blazy: 0
  block: 0
  block_class: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  contact: 0
  contextual: 0
  ctools: 0
  curtain_raiser: 0
  custom_pdf_download: 0
  custom_zip_download: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_print: 0
  excel_import_export: 0
  facets: 0
  faq: 0
  faq_ask: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filefield_paths: 0
  filter: 0
  flag: 0
  help: 0
  history: 0
  iitinap: 0
  iitinap_general: 0
  image: 0
  kint: 0
  libraries: 0
  link: 0
  login_emailusername: 0
  menu_per_role: 0
  menu_ui: 0
  metatag: 0
  metatag_app_links: 0
  metatag_dc: 0
  metatag_dc_advanced: 0
  metatag_facebook: 0
  metatag_favicons: 0
  metatag_google_plus: 0
  metatag_hreflang: 0
  metatag_mobile: 0
  metatag_open_graph: 0
  metatag_open_graph_products: 0
  metatag_twitter_cards: 0
  metatag_views: 0
  migrate: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  nocurrent_pass: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  paypal: 0
  php: 0
  phpexcel: 0
  plugin: 0
  profile: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  redis: 0
  registration_role: 0
  search_api: 0
  search_api_solr: 0
  shortcut: 0
  simple_fb_connect: 0
  site_verify: 0
  sitemap: 0
  slick: 0
  slick_ui: 0
  slick_views: 0
  smtp: 0
  social_api: 0
  social_auth: 0
  social_auth_google: 0
  statistics: 0
  system: 0
  tablefield: 0
  taxonomy: 0
  taxonomy_unique: 0
  telephone: 0
  term_migration: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_php: 0
  views_ui: 0
  workflow: 0
  workflow_access: 0
  workflow_cleanup: 0
  workflow_devel: 0
  workflow_mail: 0
  workflow_operations: 0
  workflow_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  business: 0
  bootstrap: 0
  capit: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
profile: standard
