title: 'Frequently Asked Questions'
description: ''
custom_breadcrumbs: true
expert_role:
  office: office
vocabularies:
  faq: faq
title_len: 0
suggest: 0
notify: 1
default_expert: '4'
unanswered_count: 0
categorize: 1
expert_own: '0'
notify_asker: 1
notify_asker_simplenews_tid: 0
notify_asker_simplenews_confirm: 1
notify_by_cron: 0
unanswered: 'Not answered yet.'
expert_advice: 'If you select a question, you must answer it.'
admin_advice: 'You may edit your own questions until they are answered.'
asker_advice: 'You may edit your own questions until they are answered.'
help_text: 'Add a question for our expert to answer. After being answered, your question and the answer will be displayed in the FAQ pages. If the question will not fit in the box below, please try to rephrase it.'
_core:
  default_config_hash: zg4GaUjEjDRPmr4y1qu3ZB8CMz46ArgwfjuDkVN4eBw
