app_id: '828102067324519'
app_secret: 4db24307a967e8921329e32d797634a5
api_version: v2.12
post_login_path: user
redirect_user_form: 0
disable_admin_login: 1
disabled_roles:
  administrator: administrator
  office: office
  developer: developer
  student: '0'
_core:
  default_config_hash: JJ2pkb09VwVm5U7EFJhYMC3keuZN0Le2_YRvZwZbzeQ
