app_id: '1101563849919979'
app_secret: 975ab9830a572ae08e7b1f064c0cdc07
post_login_path: user
redirect_user_form: 0
disable_admin_login: 1
disabled_roles:
  administrator: administrator
  office: office
  student: 0
  developer: 0
_core:
  default_config_hash: IyBBRoNwfQZ_KdfbBXQkQUKkZFpKxcLjXLAl2VB_tQk
