app_id: '1101563849919979'
app_secret: 0c0e2497f3d31cb331ef38cedf1b0ca5
api_version: v2.8
post_login_path: user
redirect_user_form: 0
disable_admin_login: 1
disabled_roles:
  administrator: administrator
  office: office
  developer: developer
  student: '0'
_core:
  default_config_hash: JJ2pkb09VwVm5U7EFJhYMC3keuZN0Le2_YRvZwZbzeQ
