app_id: '175964242927475'
app_secret: 8152c5a7fed9a4c23a7f422462d5b52c
api_version: v2.9
post_login_path: user
redirect_user_form: 0
disable_admin_login: 1
disabled_roles:
  administrator: administrator
  office: office
  developer: developer
  student: '0'
_core:
  default_config_hash: JJ2pkb09VwVm5U7EFJhYMC3keuZN0Le2_YRvZwZbzeQ
