smtp_on: true
smtp_host: smtp.sendgrid.net
smtp_hostbackup: ''
smtp_port: '587'
smtp_protocol: tls
smtp_username: umpp
smtp_password: rK8ZsYr9LBArh6ZSy
smtp_from: admin@unimity.com
smtp_fromname: Admin
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
_core:
  default_config_hash: fP57Sd8RjnZMVH3p_R-Yt0tC8j7Z-BuzGMIp6pmrHAI
