auth:
  social_auth_google:
    route: social_auth_google.redirect_to_google
    img_path: modules/social_auth_google/img/google_logo.svg
post_login: /user
redirect_user_form: false
disable_admin_login: true
disabled_roles:
  administrator: administrator
  office: office
  developer: developer
  student: '0'
_core:
  default_config_hash: 1tS3jCuYxV3TXQ2cq320XarjdXWprvWK5bru8DCsIUY
