apply_apply:
  workflow_author:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  student:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  office:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
apply_need_more_info:
  workflow_author:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  student:
    grant_view: true
    grant_update: true
    grant_delete: 0
  office:
    grant_view: true
    grant_update: true
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
apply_details_appended:
  workflow_author:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
  student:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  office:
    grant_view: true
    grant_update: true
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
apply_downloaded_for_department_processing:
  workflow_author:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  student:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  office:
    grant_view: true
    grant_update: true
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
apply_application_rejected:
  workflow_author:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  student:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  office:
    grant_view: true
    grant_update: true
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
apply_offer_given:
  workflow_author:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  student:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  office:
    grant_view: true
    grant_update: true
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
apply_offer_accepted:
  workflow_author:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  student:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  office:
    grant_view: true
    grant_update: true
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
apply_offer_rejected:
  workflow_author:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  student:
    grant_view: true
    grant_update: 0
    grant_delete: 0
  office:
    grant_view: true
    grant_update: true
    grant_delete: 0
  administrator:
    grant_view: 0
    grant_update: 0
    grant_delete: 0
