<?php
use Drupal\user\Entity\User;
use Drupal\profile\Entity\Profile;
use Drupal\profile\Entity\ProfileType;
use \Drupal\node\Entity\Node;

function iitinap_general_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_programme_form')  {
     $user = \Drupal::currentUser();
     $roles = $user->getRoles();
    if(in_array('office', $roles)) {
      $term = get_usr_term_id($user->id());
      if (isset ($term) && !empty ($term))  {
        if (isset($form['field_institute']['widget']['#options']))  {
          foreach ($form['field_institute']['widget']['#options'] as $tid => $term_val)  {
            if ($tid != '_none' && $tid != $term)  {
              unset ($form['field_institute']['widget']['#options'][$tid]);
            }
          } 
        }
      }
    }
  }
  if ($form_id == 'node_programme_edit_form') {
    $form['#validate'][] = 'form_validate_program';
  }
}

/**
 *Implements form_validation() for programme cck.
 */
function form_validate_program($form, &$form_state){
  $nid = $form_state->getFormObject()->getEntity()->id();
  $user = \Drupal::currentUser();
  $roles = $user->getRoles();
  if(in_array('office', $roles)) {
    $term = get_usr_term_id($user->id());
    if (isset ($term) && !empty ($term))  {
      $node = Node::load($nid);
      $langcode = $node->language()->getId();
      $ins_term_id = $node->getTranslation($langcode)->get('field_institute')->getValue()[0]['target_id'];
      if ($term != $ins_term_id)  {
        $form_state->setError($form['field_institute'], "You don't have access to modify this content");
      }
    }
  }
}

function get_usr_term_id($usr_id)  {
  $query = \Drupal::entityQuery('profile')
    ->condition('status', 1)
    ->condition('uid', $usr_id)
    ->condition('type', 'office');
  $nids = $query->execute();
  $nids = array_values($nids);
  if(isset($nids[0])) {
    $profile = Profile::load($nids[0]);
    $langcode = $profile->language()->getId();
    $term = $profile->getTranslation($langcode)->get('field_institute')->getValue()[0]['target_id']; 
  }
  if (isset($term) && !empty($term))  {
    return $term;
  }
  return ;
}